name: Tests
run-name: Run Tests
on: 
    push:
        branches: main
        paths-ignore: 'README.md'
jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Docker image
              run: docker build --target development -t test-image .

            - name: Pytest checks
              run: |
                docker run --rm test-image pytest || echo "::error::Pytest failed! Check logs."
                echo "::notice::Pytest passed"

            - name: Ruff formatting checks
              run: |
                docker run --rm test-image ruff check || echo "::error::Ruff failed! Check logs."
                echo "::notice::Ruff passed"

            - name: Bandit security checks
              run: |
                docker run --rm test-image bandit -r src || echo "::error::Bandit failed! Check logs."
                echo "::notice::Bandit passed"